services:
  - type: web
    name: scribd-dl-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install && npm run install-chrome
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://descargador-scribd.vercel.app
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
      - key: CHROME_BIN
        value: /usr/bin/google-chrome
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome
    healthCheckPath: /api/config
